# From: https://raw.githubusercontent.com/benwilcock/backstage-catalogs/main/ai-asset-catalog.yml
###############################
# SYSTEMS
###############################
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: developer-model-service
  description: "vLLM Model Service providing models for developer tools"
  tags:
    - genai
    - vllm
    - developer-tools
  links:
    - url: https://model-service.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: Developer Model Service
      type: website 
      icon: WebAsset
spec: 
  owner: user:johnmcollier
  profile:
    displayName: Developer Tools vLLM Service
---
####################################
# COMPONENTS
####################################
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ibm-granite-8b-code-instruct
  annotations:
    backstage.io/techdocs-ref: dir:.
  description: 'AI Model server popular for hosting large language models in enterprise settings. OpenAI API compatible. '
  links:
    - url: https://model-service.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: Access
      type: website
      icon: WebAssett
    - url: https://ibm-granite-8b-code-instruct-vllm.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/
      title: API URL
      type: website
      icon: WebAsset
    - url: https://docs.vllm.ai/en/stable/
      title: vLLM Documentation
      type: website
      icon: WebAsset
    - url: https://www.apache.org/licenses/LICENSE-2.0
      title: Apache-2.0 License
      type: website
      icon: WebAsset
  tags:
    - genai
spec:
  type: LLM
  owner: user:johnmcollier
  system: developer-model-service
  lifecycle: production
  providesApis:
    - model-service-api
  dependsOn:
    - resource:ibm-granite-8b-code-instruct
    - api:model-service-api
  profile:
    displayName: "IBM Granite 8b Code Model Service"
---
####################################
# RESOURCES
####################################
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ibm-granite-8b-code-instruct
  description: 'IBM Granite is a decoder-only code model for code generative tasks (e.g. fixing bugs, explaining code, documenting code. Trained with code written in 116 programming languages.'
  links:
    - url: https://github.com/ibm-granite/granite-code-models
      title: IBM Granite Code Repository
      type: website
      icon: WebAsset
  tags:
    - genai
    - ibm
    - llm
spec:
  type: ai-model
  owner: user:johnmcollier
  system: developer-model-service
  lifecycle: production
  providesApis:
    - model-service-api
  dependencyOf: 
    - component:vLLM
  profile:
    displayName: "IBM Granite Code Model"
######################################
# APIs
######################################
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: model-service-api
  title: Model Service API
  description: 'The REST API exposed by the vLLM-based model service.'
  tags:
    - api
    - openai
    - vllm
  links:
    - url: https://model-service.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com/docs
      title: Model Service API Documentation
      type: website
      icon: WebAsset
spec:
  type: api
  owner: user:johnmcollier
  system: developer-model-service
  lifecycle: production
  dependencyOf: 
    - component:ibm-granite-8b-code-instruct
  definition:
    $text: https://github.com/johnmcollier/rhdh-ai-catalog/blob/main/openapi.json
